### ISSUE TITLE
Geelong Insights

### ISSUE THREAD

**Issue by dean12** [geografia-au/movemapp_client#6]
From Hayley at Geelong:

> 
> I have received a request from the Barwon Coast Committee of Management to help them estimate economic benefits of the area in their jurisdiction.  Area of Jurisdiction - Barwon Coast
>  
> The precincts overlap and some residential areas are within their dotted boundaries on the map.  Could we just geofence the beaches, four caravan parks and river frontage?
>  
> I was wondering if you think we could extract some intel from Placemapp please?
>  
> Some ques I thought Placemapp might be able to help answer:
> - Rise in visitation during the peak Christmas/New Year period.  Easter if the data is available.
> - Any trends over time (as many years back as possible by month).
> - Proportion of visitors from surrounding suburbs (Ocean Grove and Barwon Heads locals) vs Greater Geelong residents vs people coming from outside Greater Geelong.
> - What are the main suburbs people are coming from?
> - Insights about visitation by time of day on weekday and weekend.
 

We are waiting on more information in the specific geography.

**Comment by dean12** [comment]
Specific shapes:

[geelong.geojson.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGRwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e16801d2cb2f5e754df3901781dc8d0d017fa6ab/geelong.geojson.zip)

We want to analyse the four separate areas.

<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b86c55fc8d26a73bc50fd2cc4a99322d9a9dc5b/image.png" alt="image.png" />


Note the two areas either side of the road should be combined into one.

**Comment by carson-young** [comment]
9 August refresh- Extend to the 7 areas

[Barwon Coast - Area of Jurisdiction Precincts 6-2024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09b61ca338ec23fae76f6370e7da698a0a1c3f65/Barwon%20Coast%20-%20Area%20of%20Jurisdiction%20Precincts%206-2024.pdf)
